server:
  port: 8080
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: payment_service
            uri: lb://payment_service
            predicates:
              - Path=/api/v1/payment/**
          - id: ticket_service
            uri: lb://ticket_service
            predicates:
              - Path=/api/v1/ticket/**
          - id: UserService
            uri: lb://UserService
            predicates:
              - Path=/api/v1/user2/**
          - id: VehicleService
            uri: lb://VehicleService
            predicates:
              - Path=/api/v1/item4/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

