server:
  port: 8080
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: PaymentService
            uri: lb://PaymentService
            predicates:
              - Path=/api/v1/user/**
          - id: TicketService
            uri: lb://TicketService
            predicates:
              - Path=/api/v1/item/**
          - id: UserService
            uri: lb://UserService
            predicates:
              - Path=/api/v1/user/**
          - id: VehicleService
            uri: lb://VehicleService
            predicates:
              - Path=/api/v1/item/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

